# Generated by Django 4.1.4 on 2022-12-17 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=458)),
                ('value_contract', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_procedure', models.CharField(max_length=558)),
                ('data_initiation', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('end_date_procedure', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TheContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=228)),
                ('number_NIP', models.CharField(max_length=10, null=True)),
                ('nameStreet', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProcurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_procurement', models.CharField(max_length=258)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public_procurement.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ManyToManyField(to='public_procurement.thecontractor'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_procurement.contract')),
            ],
        ),
    ]
